## Imports

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

sns.set_style("whitegrid")

In [2]:
DATA_PATH = Path("../data/MachineLearningRating_v3.txt")

df = pd.read_csv(
    DATA_PATH,
    sep="|",
    low_memory=False
)

df.head()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,MaritalStatus,Gender,Country,Province,PostalCode,MainCrestaZone,SubCrestaZone,ItemType,mmcode,VehicleType,RegistrationYear,make,Model,Cylinders,cubiccapacity,kilowatts,bodytype,NumberOfDoors,VehicleIntroDate,CustomValueEstimate,AlarmImmobiliser,TrackingDevice,CapitalOutstanding,NewVehicle,WrittenOff,Rebuilt,Converted,CrossBorder,NumberOfVehiclesInFleet,SumInsured,TermFrequency,CalculatedPremiumPerTerm,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,0.01,Monthly,25.0000,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,0.01,Monthly,25.0000,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,0.01,Monthly,25.0000,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,119300.00,Monthly,584.6468,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,119300.00,Monthly,584.6468,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000098 entries, 0 to 1000097
Data columns (total 52 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   UnderwrittenCoverID       1000098 non-null  int64
 1   PolicyID                  1000098 non-null  int64
 2   TransactionMonth          1000098 non-null  str
 3   IsVATRegistered           1000098 non-null  bool
 4   Citizenship               1000098 non-null  str
 5   LegalType                 1000098 non-null  str
 6   Title                     1000098 non-null  str
 7   Language                  1000098 non-null  str
 8   Bank                      854137 non-null   str
 9   AccountType               959866 non-null   str
 10  MaritalStatus             991839 non-null   str
 11  Gender                    990562 non-null   str
 12  Country                   1000098 non-null  str
 13  Province                  1000098 non-null  str
 14  PostalCode                1000098 non-null  int64
 15  MainCrestaZone            1000098 non-null  str
 16  SubCrestaZone             1000098 non-null  str
 17  ItemType                  1000098 non-null  str
 18  mmcode                    999546 non-null   float64
 19  VehicleType               999546 non-null   str
 20  RegistrationYear          1000098 non-null  int64
 21  make                      999546 non-null   str
 22  Model                     999546 non-null   str
 23  Cylinders                 999546 non-null   float64
 24  cubiccapacity             999546 non-null   float64
 25  kilowatts                 999546 non-null   float64
 26  bodytype                  999546 non-null   str
 27  NumberOfDoors             999546 non-null   float64
 28  VehicleIntroDate          999546 non-null   str
 29  CustomValueEstimate       220456 non-null   float64
 30  AlarmImmobiliser          1000098 non-null  str
 31  TrackingDevice            1000098 non-null  str
 32  CapitalOutstanding        1000096 non-null  str
 33  NewVehicle                846803 non-null   str
 34  WrittenOff                358197 non-null   str
 35  Rebuilt                   358197 non-null   str
 36  Converted                 358197 non-null   str
 37  CrossBorder               698 non-null      str
 38  NumberOfVehiclesInFleet   0 non-null        float64
 39  SumInsured                1000098 non-null  float64
 40  TermFrequency             1000098 non-null  str
 41  CalculatedPremiumPerTerm  1000098 non-null  float64
 42  ExcessSelected            1000098 non-null  str
 43  CoverCategory             1000098 non-null  str
 44  CoverType                 1000098 non-null  str
 45  CoverGroup                1000098 non-null  str
 46  Section                   1000098 non-null  str
 47  Product                   1000098 non-null  str
 48  StatutoryClass            1000098 non-null  str
 49  StatutoryRiskType         1000098 non-null  str
 50  TotalPremium              1000098 non-null  float64
 51  TotalClaims               1000098 non-null  float64
dtypes: bool(1), float64(11), int64(4), str(36)
memory usage: 390.1 MB

In [4]:
object_cols = df.select_dtypes(include="object").columns

print(object_cols)
print(len(object_cols))

Index(['TransactionMonth', 'Citizenship', 'LegalType', 'Title', 'Language',
       'Bank', 'AccountType', 'MaritalStatus', 'Gender', 'Country', 'Province',
       'MainCrestaZone', 'SubCrestaZone', 'ItemType', 'VehicleType', 'make',
       'Model', 'bodytype', 'VehicleIntroDate', 'AlarmImmobiliser',
       'TrackingDevice', 'CapitalOutstanding', 'NewVehicle', 'WrittenOff',
       'Rebuilt', 'Converted', 'CrossBorder', 'TermFrequency',
       'ExcessSelected', 'CoverCategory', 'CoverType', 'CoverGroup', 'Section',
       'Product', 'StatutoryClass', 'StatutoryRiskType'],
      dtype='str')
36

C:\Users\Dataencoder\AppData\Local\Temp\ipykernel_14732\113848702.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include="object").columns

In [5]:
for col in object_cols:
    df[col] = df[col].astype(str).str.strip()

In [6]:
df.replace(
    ["", " ", "nan", "None"],
    np.nan,
    inplace=True
)

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,MaritalStatus,Gender,Country,Province,PostalCode,MainCrestaZone,SubCrestaZone,ItemType,mmcode,VehicleType,RegistrationYear,make,Model,Cylinders,cubiccapacity,kilowatts,bodytype,NumberOfDoors,VehicleIntroDate,CustomValueEstimate,AlarmImmobiliser,TrackingDevice,CapitalOutstanding,NewVehicle,WrittenOff,Rebuilt,Converted,CrossBorder,NumberOfVehiclesInFleet,SumInsured,TermFrequency,CalculatedPremiumPerTerm,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,NaN,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,0.01,Monthly,25.0000,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,NaN,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,0.01,Monthly,25.0000,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,NaN,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,0.01,Monthly,25.0000,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,NaN,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,119300.00,Monthly,584.6468,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,NaN,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,119300.00,Monthly,584.6468,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000093,31520,389,2015-04-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,Single,Male,South Africa,Western Cape,7493,Karoo 1 (Northeast of Cape Town),Northeast of CT,Mobility - Motor,4614100.0,Passenger Vehicle,2013,B.A.W,SASUKA 2.7i (16 SEAT),4.0,2693.0,110.0,B/S,4.0,2013/01/01 12:00:00 AM,NaN,Yes,No,0,More than 6 months,No,No,No,NaN,NaN,500000.00,Monthly,395.8481,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,347.235175,0.0
1000094,31520,389,2015-06-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,Single,Male,South Africa,Western Cape,7493,Karoo 1 (Northeast of Cape Town),Northeast of CT,Mobility - Motor,4614100.0,Passenger Vehicle,2013,B.A.W,SASUKA 2.7i (16 SEAT),4.0,2693.0,110.0,B/S,4.0,2013/01/01 12:00:00 AM,NaN,Yes,No,0,More than 6 months,No,No,No,NaN,NaN,500000.00,Monthly,395.8481,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,347.235175,0.0
1000095,31520,389,2015-08-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,Single,Male,South Africa,Western Cape,7493,Karoo 1 (Northeast of Cape Town),Northeast of CT,Mobility - Motor,4614100.0,Passenger Vehicle,2013,B.A.W,SASUKA 2.7i (16 SEAT),4.0,2693.0,110.0,B/S,4.0,2013/01/01 12:00:00 AM,NaN,Yes,No,0,More than 6 months,No,No,No,NaN,NaN,500000.00,Monthly,395.8481,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,347.235175,0.0
1000096,31519,389,2014-07-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,Single,Male,South Africa,Western Cape,7493,Karoo 1 (Northeast of Cape Town),Northeast of CT,Mobility - Motor,4614100.0,Passenger Vehicle,2013,B.A.W,SASUKA 2.7i (16 SEAT),4.0,2693.0,110.0,B/S,4.0,2013/01/01 12:00:00 AM,NaN,Yes,No,0,More than 6 months,No,No,No,NaN,NaN,5000000.00,Monthly,2.6391,No excess,Passenger Liability,Passenger Liability,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,2.315000,0.0
1000097,31519,389,2015-02-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,Single,Male,South Africa,Western Cape,7493,Karoo 1 (Northeast of Cape Town),Northeast of CT,Mobility - Motor,4614100.0,Passenger Vehicle,2013,B.A.W,SASUKA 2.7i (16 SEAT),4.0,2693.0,110.0,B/S,4.0,2013/01/01 12:00:00 AM,NaN,Yes,No,0,More than 6 months,No,No,No,NaN,NaN,5000000.00,Monthly,2.6391,No excess,Passenger Liability,Passenger Liability,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,2.315000,0.0

In [7]:
date_cols = [
    "TransactionMonth",
    "VehicleIntroDate"
]

for col in date_cols:
    df[col] = pd.to_datetime(
        df[col],
        errors="coerce"
    )

C:\Users\Dataencoder\AppData\Local\Temp\ipykernel_14732\2254699722.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(

In [10]:
# df[date_cols].info()

In [9]:
binary_cols = [
    "AlarmImmobiliser",
    "TrackingDevice",
    "WrittenOff",
    "Rebuilt",
    "Converted",
    "CrossBorder",
    "NewVehicle",
    "IsVATRegistered"
]

mapping = {
    "Yes": 1,
    "No": 0,
    "True": 1,
    "False": 0
}

for col in binary_cols:
    df[col] = df[col].map(mapping)

In [12]:
# df[binary_cols].head()

In [13]:
for col in df.columns:
    if df[col].dtype == "object":
        print(col)

In [15]:
numeric_cols = [
    "TotalPremium",
    "TotalClaims",
    "CustomValueEstimate",
    "RegistrationYear",
    "kilowatts",
    "cubiccapacity",
    "NumberOfDoors",
    "Cylinders",
    "SumInsured",
    "CalculatedPremiumPerTerm"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

In [17]:
# df[numeric_cols].info()

In [18]:
missing_values = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

missing_values.head(30)

IsVATRegistered            1000098
NewVehicle                 1000098
NumberOfVehiclesInFleet    1000098
CrossBorder                 999400
Citizenship                 895210
CustomValueEstimate         779642
Converted                   641901
Rebuilt                     641901
WrittenOff                  641901
Bank                        145961
AccountType                  40232
Gender                        9536
MaritalStatus                 8259
make                           552
VehicleType                    552
mmcode                         552
bodytype                       552
kilowatts                      552
NumberOfDoors                  552
VehicleIntroDate               552
Cylinders                      552
Model                          552
cubiccapacity                  552
CapitalOutstanding               2
SubCrestaZone                    0
ItemType                         0
PostalCode                       0
MainCrestaZone                   0
Language                         0
UnderwrittenCoverID              0
dtype: int64

In [19]:
missing_percent = (
    df.isnull()
      .mean() * 100
).sort_values(ascending=False)

missing_percent.head(30)

IsVATRegistered            100.000000
NewVehicle                 100.000000
NumberOfVehiclesInFleet    100.000000
CrossBorder                 99.930207
Citizenship                 89.512228
CustomValueEstimate         77.956560
Converted                   64.183810
Rebuilt                     64.183810
WrittenOff                  64.183810
Bank                        14.594670
AccountType                  4.022806
Gender                       0.953507
MaritalStatus                0.825819
make                         0.055195
VehicleType                  0.055195
mmcode                       0.055195
bodytype                     0.055195
kilowatts                    0.055195
NumberOfDoors                0.055195
VehicleIntroDate             0.055195
Cylinders                    0.055195
Model                        0.055195
cubiccapacity                0.055195
CapitalOutstanding           0.000200
SubCrestaZone                0.000000
ItemType                     0.000000
PostalCode                   0.000000
MainCrestaZone               0.000000
Language                     0.000000
UnderwrittenCoverID          0.000000
dtype: float64

In [20]:
missing_percent = (
    df.isnull()
      .mean() * 100
).sort_values(ascending=False)

missing_percent.head(30)

IsVATRegistered            100.000000
NewVehicle                 100.000000
NumberOfVehiclesInFleet    100.000000
CrossBorder                 99.930207
Citizenship                 89.512228
CustomValueEstimate         77.956560
Converted                   64.183810
Rebuilt                     64.183810
WrittenOff                  64.183810
Bank                        14.594670
AccountType                  4.022806
Gender                       0.953507
MaritalStatus                0.825819
make                         0.055195
VehicleType                  0.055195
mmcode                       0.055195
bodytype                     0.055195
kilowatts                    0.055195
NumberOfDoors                0.055195
VehicleIntroDate             0.055195
Cylinders                    0.055195
Model                        0.055195
cubiccapacity                0.055195
CapitalOutstanding           0.000200
SubCrestaZone                0.000000
ItemType                     0.000000
PostalCode                   0.000000
MainCrestaZone               0.000000
Language                     0.000000
UnderwrittenCoverID          0.000000
dtype: float64

In [26]:
df["LossRatio"] = (
    df["TotalClaims"] /
    df["TotalPremium"]
)

In [27]:
df["LossRatio"] = df["LossRatio"].replace(
    [np.inf, -np.inf],
    np.nan
)

In [28]:
df["Margin"] = (
    df["TotalPremium"] -
    df["TotalClaims"]
)

In [29]:
df["VehicleAge"] = (
    2015 - df["RegistrationYear"]
)

In [30]:
df["HasClaim"] = (
    df["TotalClaims"] > 0
).astype(int)

In [31]:
CLEAN_PATH = "../data/cleaned_insurance_data.csv"

df.to_csv(
    CLEAN_PATH,
    index=False
)